### ISSUE TITLE
Type of Bravais basis vectors vs type of Sublat sites

### ISSUE THREAD

**Issue by BacAmorim** [pablosanjose/Elsa.jl#11]
In the `Bravais` type, the Bravais basis vectors are stored as a SMatrix with entries of type `Float64`. In the`Sublat` type, the site positions are stored as `SVector`'s with entries of general type `T`. Wouldn't it be more consistent for the Bavais basis vectors to be stored also with entries of type `T`?

**Comment by pablosanjose** [comment]
Thanks for the suggestion. That was indeed the case before the recent refactor #6. I ended up making `Bravais` specific to make code a little bit less complex, but I agree with you, that was a bad call. Unfortunately I haven't been very disciplined in my commits during the refactor, so I don't think I can undo that decision with a simple revert. I will do a PR as soon as I can to address this.

**Comment by pablosanjose** [comment]
Hey Bruno, I just went ahead and merged the PR, as it was rather simple. Thanks again for bringing this to my attention!
