### ISSUE TITLE
Simplify static encoding of orbital dimensions

### ISSUE THREAD

**Issue by pablosanjose** [pablosanjose/Elsa.jl#18]
There is an inherent fragility and unnecessary complexity in the current design of heterogenous orbital systems. 

To avoid forcing the user to explicitly state the orbital dimensions of the different sublattices, that information is inferred from the model provided by the user. Each term in the model is sampled at a given point (the origin) to find out the dimensions of the hopping or onsite matrix, that type is stored in a tuple of sample types (inside `sys.sysinfo`), and the dimension of subsequent terms is checked for consistency with preceding terms. 

This method is fragile: as soon as the model provided by the user is not type stable, this scheme fails without any warning. It is also unnecessarily complex: instead of statically storing the orbital dimensions of each sublattice, we are forced to store the dimension of each term, with potential redundancies if there are several terms referencing the same sublattices.

A much cleaner approach would be to force the user to declare sublattice dimensions explicitly
```
system = System(Sublat{2}((0,0), name = :A), Sublat{1}((1,0), name = :B), Model(Hopping(@SMatrix[1;2], sublats = (1,2)))
```
The `System` type would then encode the orbital parameters as a `Tuple{2,1}` parameter, and the model would be cast onto the appropriate `SMatrix{N,M}` type each time it is evaluated, erroring if it is type unstable or inconsistent (with a useful message to boot).

For ease of use, we could define `Sublat(...)` as an alias for `Sublat{1}(...)`.

Another advantage is that the `System` type would also encode statically the number of sublattices (I'm not sure where that could be useful though)

**Comment by BacAmorim** [comment]
Just a suggestion: 

Wouldn't it make more sense for the number of orbitals of the different sublattices be stored outside of the Sublattice itself? The sublattice is a property of the crystalline structure of the system, while the number of orbitals is model dependent. I am thinking for example of the different models for monolayer TMDs: both 11 and 3 orbital models are used, but the crystal structure is the same. (This is probably a bad example as the 3 orbital model lives in a triangular lattice). 

A possibility to make this split between Crystalline Structure and Tight-Binding Model would be to define a Model as a Number of orbitals (storing the sublattice dimensions) + OnSite terms + Hopping terms. Maybe a Model could be made parametric on the number of orbitals, such that Model{{5, 3, 3}, +terms...} would be the 11 band model for TMDs, while Model{{3, 0, 0}, +terms...} would be the 3 band model.

Would this make sense?

**Comment by pablosanjose** [comment]
Hi Bruno, 

Thanks for your suggestion! Yes, what you say makes sense, and I think I would indeed prefer it to work that way.  I would like to figure out a simple API for your proposal. With the new API (current master) I can do things like this
```
hamiltonian(LatticePresets.honeycomb(orbitals = (:up,:down)), onsite([1 2; 3 4]) + hopping([2 3; 4 5]))
```
With something like your approach I would need to do 
```
hamiltonian(LatticePresets.honeycomb(), model(onsite([1 2; 3 4]) + hopping([2 3; 4 5]), orbitals = (:up, :down)))
```
This requires adding a new command (model). Or maybe we could do this?
```
hamiltonian(LatticePresets.honeycomb(), onsite([1 2; 3 4]) + hopping([2 3; 4 5]), orbitals = (:up, :down))
```
That would be nicer, I think. Let me think for a bit, and see if there is any conflict with any other functionality

PS: By the way, as you see there have been lots of changes lately. There are docstrings that you can check out, but no starting guide yet. Do let me know what you think if you check it out. The new api is essentially `bravais`, `sublat`, `lattice`, `hamiltonian`, `unitcell`, `supercell` and `bloch(!)`.

**Comment by BacAmorim** [comment]
I think eitheir approach would be fine, but maybe the second one is cleaner.

> PS: By the way, as you see there have been lots of changes lately. There are docstrings that you can check out, but no starting guide yet. Do let me know what you think if you check it out. The new api is essentially bravais, sublat, lattice, hamiltonian, unitcell, supercell and bloch(!). Beyond this we have the new bandstructure/green function functionality, still under development.

I haven't checked the code since the summer, but I intend to get back to studying it next month!

**Comment by BacAmorim** [comment]
Maybe it could also be interesting to allow for an optional interface like this:

(suppose there is a preset for the 11 band model for monolayer MX2)

`hamiltonian(
LatticePresets.MX2(), 
terms... , 
orbitals = ((:dx2y2, :dxy, :dz2, :dxz, :dyz), (:px, :py, :pz), (:px, :py, :pz))`

such that it would be infered the not only the number of orbitals per sublattice (5, 3, 3), but also the kind of orbitals involved, which could be stored for example on the SystemInfo

**Comment by pablosanjose** [comment]
This is precisely the idea, and how it currently works (although in `lattice`, not in `hamiltonian`). Not only it allows to label orbitals by name, but it also has the benefit of communicating *static* information about the orbitals (in the length of the tuples).

You have convinced me, I'll try to implement it ASAP. My only remaining concern was that there could be some ambiguity as to which sublattice one refers to as first, second, third... But there is a clean way around that, to use sublattice names (which are currently forced to be unique), and allow also an input such as 
```
hamiltonian( LatticePresets.MX2(), terms... , orbitals = (:M => (:dx2y2, :dxy, :dz2, :dxz, :dyz), :X1 => (:px, :py, :pz), :X2 =>(:px, :py, :pz))
```

**Comment by pablosanjose** [comment]
See also #22 for a followup issue caused by this proposal
