### ISSUE TITLE
[DOC] A simpler simple example

### ISSUE THREAD

**Issue by Datseris** [pablosanjose/Elsa.jl#2]
Currently the `Simple` example in the docs is simple only for someone that is already a master of Elsa. For a new user it is not that simple and in fact could turn away users. My suggestion is to reform the simple example into something simpler:

1. Each code command should be different line of code.
1. Break the code into _definitions_ (first define the  Bravains, the sublattice atoms, etc.). Explain _every_ single line of code. 
1. Avoid magic constants. Instead of using `LatticeConstant(0.246))` define `a0 = 0.246` in a different line and write `LatticeConstant(a0)`. 
1. Try to not exceed 92 chars per line when writing code
1. After the lattice is created explain the listed fields:
```
Lattice{Float64,2,2} : 2D lattice in 2D space with Float64 sites
    Bravais vectors  : ((0.5, 0.866025), (-0.5, 0.866025))
    Sublattice names : (:A, :B)
    Total sites      : 2
    Total links      : 5
    Coordination     : 3.0
```
What is coordination? why are the total links 5? what does total links even mean?

**Comment by pablosanjose** [comment]
Thanks for the recommendations @Datseris. I've pushed an update to index.md, please let me know if it is now clearer.

**Comment by Datseris** [comment]
Thanks I am reading it now. It also explains many of the questions in #3 .

This closes the current issue, the tutorial now indeed explains everything to create a simple lattice.
