### ISSUE TITLE
Question: getting the wavefunction at very specific sites

### ISSUE THREAD

**Issue by Datseris** [pablosanjose/Elsa.jl#4]
Hi there. I got a question about how can I go about achieving the following:

Let's say that I have created a graphene lattice (any shape is fine for now). I want to get:
1. All site indices that belong only to A sublattice. Lets call this vector `Ai`.
2. All positions of sites `Ai`.
3. In the same sorting as `Ai`, I want the indices of the B sublattice, such that the site `Bi[i]` is the lattice site directly below lattice site `Ai[i]`. `B[i]` can be `missing` if site `Ai[i]` does not have a below nearest neighbor.

How easy is the above? Firstly let's simply talk about how easy is the above **only for (1) and (2)**. Then we can discuss (3), which seems to be a generally very difficult case.

---

For the actual physical problem. I want to initialize a wavepacket such that it has a very specific value on the A sub-lattice and the B sublattice has the same value but multiplied with some complex number. Since the value in the two sublattices must be "the same" I need to get all A sites and all their basis-neighbors as well.

**Comment by pablosanjose** [comment]
So with the current design a given site is identified by two indices, its sublattice index (or `name::Symbol`) and its index *within* its sublattice. I'm not too sure the type of list `Ai` you have in mind.

For site positions you now have `sitepositions(sys, sublat)` as part of the exported System API. It returns a vector of site positions for sublattice `sublat` (where `sublat` is a sublattice index or name). Similarly, `sitepositions(sys)` returns a vector of all the `sites(sys, sublat)` for all sublattices, and `sitepositions(sys, sublat, siteindex)` gives the position of a single site (maybe we should call that `siteposition`?)

For neighbors you can also now use `neighbors(sys, sublat, siteindex)`, which gives you, a vector of tuples, with the sublattice and the site indices of the neighbors of the input site. Note that neighborhood relationship is defined by hoppings. If there is no hopping in your model between two sites, they will not be considered neighbors, regardless of their distance.

Example:
```
julia> sys = System(:honeycomb, Model(Hopping(1))) |> grow(region = Region(:square, 2))
System{2,0,Float64,Complex{Float64}} : 0D system in 2D space
  Bravais vectors     : ()
  Sublattice names    : (:A, :B)
  Sublattice orbitals : (1, 1)
  Total sites         : 10 [Float64]
  Total hoppings      : 50 [Complex{Float64}]
  Coordination        : 5.0

julia> neighbors(sys, 1, 4)
4-element Array{Tuple{Int64,Int64},1}:
 (1, 2)
 (1, 5)
 (2, 3)
 (2, 5)
```

If you need only a specific target sublattice, you can use the `targetsublat` keyword
```
julia> neighbors(sys, 1, 4, targetsublat = :A)
2-element Array{Tuple{Int64,Int64},1}:
 (1, 2)
 (1, 5)
```

If you want the positions of the neighbor sites you can broadcast into `sitepositions`
```
julia> nn = neighbors(sys, 1, 4); sitepositions.(sys, nn)
4-element Array{StaticArrays.SArray{Tuple{2},Float64,1,2},1}:
 [0.0, -0.288675]
 [-0.5, 0.57735] 
 [-0.5, -0.57735]
 [-1.0, 0.288675]
```

**Comment by pablosanjose** [comment]
I believe we can close this now.
